name: phpcs

on:
  pull_request:
    branches: [develop]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
      - name: Check code style
        run: |
          phpcs --report=code --standard=PSR2 ./home/system/php_libs/marketing.php
      
