name: php-cs-fixer

on:
  pull_request:
    branches: [develop]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version
      - uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**.php"
          phpcs_path: php phpcs.phar
          standard: PSR2  # phpcs.xml
